# Generated by Django 2.1 on 2024-04-05 04:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 4, 34, 7, 489312, tzinfo=utc)),
        ),
    ]
